### ISSUE TITLE
About the repo name

### ISSUE THREAD

**Issue by SivilTaram** [CPR-RSS/CPR-RSS.github.io#1]
One suggestion is **Catch Overall Conferences (COCO)**. And do you need a front-end developer ?

**Comment by XgDuan** [comment]
Emmm, that's a really cool name (but we won't take it, hahaha).

For the frontend, I would like to build a simple webpage when finished most of the top AI conference (Maybe we would like to ask for your help then).

**Comment by XgDuan** [comment]
BTW, why not give us a star. @SivilTaram

**Comment by SivilTaram** [comment]
As you wish O_P

**Comment by SivilTaram** [comment]
Any updates now ?

**Comment by XgDuan** [comment]
No, but we have update plans next month

**Comment by XgDuan** [comment]
UPDATED @SivilTaram

**Comment by XgDuan** [comment]
This repo is renamed as paper-gem (**paper** readin**G** syst**EM**)! Build up your academic muscle here!!!
