### ISSUE TITLE
ICLR2020

### ISSUE THREAD

**Issue by h-jia** [CPR-RSS/CPR-RSS.github.io#3]
Hi, thanks for your work. It is very useful for me. 
Is there any plan for ICLR 2020?

**Comment by XgDuan** [comment]
Yes. But I am working hard on my current project. Maybe I will prepare the ICLR2020 paper RSS in the early June (Or you can download the code, run it for ICLR2020 and push the results to this repo)

**Comment by XgDuan** [comment]
Done!

**Comment by h-jia** [comment]
Hi,

Thanks for uploading the ICLR2020. It works perfect for me. 

Unfortunately when running cmd `python main.py -c nips -y 2020`, I met following errors:

```
list index out of range
list index out of range
100%|█████████████████████████████████████| 2592/2592 [00:00<00:00, 3256.54it/s]
Parse https://nips.cc/Conferences/2020/Schedule; spotlight: 280, Oral: 106, Poster: 1899, Overall: 2285, faild: 2285
0it [00:00, ?it/s]
```

Any suggestions will much appreciated!

**Comment by XgDuan** [comment]
If you open the page `https://nips.cc/Conferences/2020/Schedule' by hand, you will find that there are only some placeholders, and no paper actually released. We have to wait until the NeurIPS 2020 committee releasing these papers (maybe after the conference).

**Comment by XgDuan** [comment]
If you want to read NeurIPS2020's paper immediately, the only way is to follow the authors on arXiv.

**Comment by h-jia** [comment]
I found a fork version based on your project: [https://lbzhang.github.io/conference-paper-rss/rss_source/nips2020.xml](https://lbzhang.github.io/conference-paper-rss/rss_source/nips2020.xml)

Thanks 🙏
